#!/bin/bash
PART=$1
if [ $2 = "Start" ]
then
  FS_TYPE=`lsblk -o name,fstype | grep "${PART} " | awk '{print $2}'`
  if [ ! -z "${FS_TYPE}" ]
  then
    FS_PRE_LABEL=`ls -lS /dev/disk/by-label | grep ${PART}$ | awk '{print $9}'`
    FS_LABEL=`echo -ne ${FS_PRE_LABEL}`
    if [ -z "${FS_LABEL}" ]
    then
      /bin/mkdir /media/${PART}
      /bin/mount /dev/${PART} /media/${PART} -o ro
    else
      /bin/mkdir /media/"${FS_LABEL}"
      /bin/mount /dev/${PART} /media/"${FS_LABEL}" -o ro
    fi
  fi
fi

if [ $2 = "Stop" ]
then
  FS_MOUNTPOINT=`mount | grep "${PART} " | grep -o -P '(?<=on ).*(?= type)'`
  /bin/umount /dev/${PART}
  /bin/rm -r "${FS_MOUNTPOINT}"
fi
